name: tfr
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - torch==2.0.1
  - torchvision==0.15.2
  - torchaudio==2.0.2
  - pillow
  - cudatoolkit=11.8  # Match this with your CUDA version
  - pip
  - pip:
      - torchinfo  # if you need to print model summaries or any other pip packages